import 'regenerator-runtime/runtime';
import { createRoot } from 'react-dom/client';
import './locales/i18n';
import App from './App';
// gui's theme + base sheet. GENERATED by the compiler on every `vite build`
// (vite.config.ts, outputCSS) and committed, because the dev server does not run
// the compiler and an import has to resolve on a fresh clone. A diff here means
// a gui or gui-config bump moved the theme — read it, don't hand-edit it.
// First, so the app's own CSS below still wins where the two touch the same names.
import './gui.css';
import './style.css';
import './mobile.css';
import { ApiErrorBoundaryProvider } from './hooks/ApiErrorBoundaryContext';
import 'katex/dist/katex.min.css';
import 'katex/dist/contrib/copy-tex.js';

const container = document.getElementById('root');
const root = createRoot(container);

root.render(
  <ApiErrorBoundaryProvider>
    <App />
  </ApiErrorBoundaryProvider>,
);
