import 'regenerator-runtime/runtime';
import { createRoot } from 'react-dom/client';
import './locales/i18n';
import App from './App';
// gui's theme + base sheet. GENERATED by the compiler on every `vite build`
// (vite.config.ts, outputCSS) and committed, because the dev server does not run
// the compiler and an import has to resolve on a fresh clone. A diff here means
// a gui or gui-config bump moved the theme — read it, don't hand-edit it.
// First, so the app's own CSS below still wins where the two touch the same names.
import './gui.css';
import './style.css';
import './mobile.css';
import { ApiErrorBoundaryProvider } from './hooks/ApiErrorBoundaryContext';
import 'katex/dist/katex.min.css';
import 'katex/dist/contrib/copy-tex.js';
import { apply as applyAppearance, read as readAppearance } from '@hanzo/appearance/state';
import { referrerProduct } from './utils/referrerProduct';

// A person's text size and density, on the document before React renders.
//
// The Next apps inline @hanzo/appearance's bootScript() in <head>, which runs
// before ANY bundle. A Vite SPA has no server-rendered markup to flash — the
// shell in index.html is a loading screen — so applying here, ahead of the
// first render, is the same guarantee without hand-copying the script's body
// into index.html beside the theme one. Two copies of one rule is how they
// drift, and this file is where the bundle first gets to speak.
applyAppearance(readAppearance());

// Which Hanzo surface sent this visitor, read while the URL still says so.
//
// `?hz_ref=` is stamped on chat_started, and that is the LAST thing to happen:
// the composer clears the query string within ~100ms of mounting, and the silent
// SSO probe can take the document to hanzo.id before even that. By send time
// there is nothing left to read. The call pins it to the session, so it survives
// both, and reading it early is the whole of what it needs.
referrerProduct();

const container = document.getElementById('root');
const root = createRoot(container);

root.render(
  <ApiErrorBoundaryProvider>
    <App />
  </ApiErrorBoundaryProvider>,
);
