services:
  api:
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - type: bind
        source: ./chat.yaml
        target: /app/chat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      # Add volume mount for client dist assets
      - ./client/dist/assets:/app/client/dist/assets
  meilisearch:
    ports:
      - "7700:7700"