import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
await page.goto('http://localhost:5220/c/new', { waitUntil: 'domcontentloaded', timeout: 60000 });
await page.waitForTimeout(8000);
const CTRL = 'button, a, [role="tab"], [role="button"], input, textarea, select, summary';
const a = await page.evaluate((CTRL) => document.querySelectorAll(CTRL).length, CTRL);
const b = await page.evaluate((sel) => document.querySelectorAll(sel).length, CTRL);
const c = await page.evaluate(() => document.querySelectorAll('button, a, [role="tab"], [role="button"], input, textarea, select, summary').length);
console.log(JSON.stringify({ passedAsCTRL: a, passedAsSel: b, inlined: c }));
await browser.close();
