# Development-specific overrides for Docker Compose
# Use with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    environment:
      - NODE_ENV=development
      - DEBUG_LOGGING=true
      - PORT=${PORT:-3080}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt}
    volumes:
      # Mount source code for hot reloading
      - ../api:/app/api:delegated
      - ../client:/app/client:delegated
      - ../packages:/app/packages:delegated
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/api/node_modules
      - /app/client/node_modules
      - /app/packages/data-provider/node_modules
      - /app/packages/data-schemas/node_modules
      - /app/packages/api/node_modules
    command: npm run backend:dev

  meilisearch:
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt}

  mongodb:
    ports:
      - "27017:27017"  # Expose MongoDB for local development tools