[project]
name = "hanzo-mcp-code-executor"
version = "0.1.0"
description = "Hanzo Code Executor MCP Server"
requires-python = ">=3.10"
dependencies = [
    "mcp>=0.1.0",
    "httpx>=0.27.0",
]

[project.scripts]
hanzo-code-executor = "hanzo_code_executor:main"