{{- if .Values.chat.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat.fullname" $ }}-config
data:
  chat.yaml: |
{{ .Values.chat.configYamlContent | toYaml | indent 4 }}

{{- end }}